First draft of Art History YAML
HoagieClub/plan pull request #10
Opened 2024-10-24 00:04 UTC by aaronjyang

First draft of Art History YAML

2024-10-24 02:37 UTC, issacli-0821 commented on backend/minors/ART.yaml
> +  - ART
We won't need this. If a requirement has a `req_list`, then it cannot have a `course_list` or `dept_list`

2024-10-24 02:37 UTC, issacli-0821 commented on backend/minors/ART.yaml
> +    max_counted: 5
This should be 1

2024-10-24 02:37 UTC, issacli-0821 commented on backend/minors/ART.yaml
> +    max_counted: 5
This should be 1 too

2024-10-24 02:38 UTC, issacli-0821 commented on backend/minors/ART.yaml
> +    max_counted: 5
This should be 1

2024-10-24 02:38 UTC, issacli-0821 commented on backend/minors/ART.yaml
> +    - ART 3*
This should be ART 4**

2024-10-24 02:40 UTC, issacli-0821 commented on backend/minors/ART.yaml
> +  min_needed: 5
Let's add another subreq here that is just general ART classes that encode the requirement that 5 ART courses are needed

2024-10-24 02:41 UTC, issacli-0821 commented on backend/minors/ART.yaml
> +  min_needed: 5
With the above change, we would change `min_needed` to 4 to reflect the fact that there are 4 children reqs that need to be satisfied: "Introductory", "200-level", "400-level", "5 courses". Also make sure we have `double_counting_allowed` set to true

2024-10-24 02:42 UTC, issacli-0821 requested changes
Left some comments for this PR. This minor has some slightly strange requirements, so it's kinda hard to encode the info. Let me know if you can think of a better way to do it!

2024-10-24 02:48 UTC, issacli-0821 commented on backend/minors/ART.yaml
> +  max_counted: 0
Let's change this to 1. We generally don't want `max_counted` = 0

2024-10-24 02:49 UTC, issacli-0821 commented on backend/minors/ART.yaml
> +    ART as the first or only subject code).
Let's add a `no_req` requirement and an editor's note in the explanation. For an example, check out [URB.yaml](https://github.com/HoagieClub/plan/blob/3f6b6d2f530c825d6cbc8c43d103d1001a5ef9ba/backend/certificates/URB.yaml#L340-L355)

2024-10-27 04:41 UTC, G-Marin approved these changes

2024-10-30 05:17 UTC, issacli-0821 requested changes
Left some comments. Let me know if you have any questions!

2024-10-30 05:17 UTC, issacli-0821 commented on backend/minors/ART.yaml
> +  min_needed: 7
`min_needed` should be 4 cuz all the subreqs must be satisfiede

2024-10-30 05:17 UTC, issacli-0821 commented on backend/minors/ART.yaml
> +    designations are included in the Registrar’s course listings, and will
Let's consolidate these into one requirement since their details are the same. We can name it "Distribution Area" or something similar

2024-10-30 05:17 UTC, issacli-0821 commented on backend/minors/ART.yaml
> +    - ART100
Add a space between ART and 100

2024-10-30 05:17 UTC, issacli-0821 commented on backend/minors/ART.yaml
> +
Add "< br > < br >" for new lines. For reference, you can check out this [PHY.yaml](https://github.com/HoagieClub/plan/pull/13/files)

2024-10-30 05:40 UTC, issacli-0821 approved these changes
Looks good! Thanks!

2024-10-30 05:40 UTC, merged