French Minor
HoagieClub/plan pull request #27
Opened 2024-10-30 18:44 UTC by hannahchoi05

2024-10-30 23:28 UTC, ggchiriac commented on backend/minors/FRE.yaml
> +  min_needed: 5
Some errors here

2024-10-30 23:28 UTC, ggchiriac requested changes
Some errors with max_counted, min_needed.

2024-10-31 04:04 UTC, issacli-0821 commented on backend/minors/FRE.yaml
> +    min_needed: 0
`max_counted` should be 2 and `min_needed` can just be 1

2024-10-31 04:05 UTC, issacli-0821 commented on backend/minors/FRE.yaml
> +        min_counted: 0
We can set this to 1 too, generally we don't want these fields to be 0

2024-10-31 04:06 UTC, issacli-0821 requested changes
Left some comments. Let me know if you have any questions

2024-10-31 04:06 UTC, issacli-0821 commented on backend/minors/FRE.yaml
> +        min_counted: 0
We can set this to 1 too, generally we don't want these fields to be 0

2024-10-31 04:06 UTC, issacli-0821 commented on backend/minors/FRE.yaml
> +    min_needed: 0
`max_counted` should be 2 and `min_needed` can just be 1

2024-10-31 04:06 UTC, issacli-0821 commented on backend/minors/FRE.yaml
> +    max_counted: 1
This should be 5

2024-10-31 14:58 UTC, issacli-0821 requested changes
Left one comment and then we should be good!

2024-10-31 14:58 UTC, issacli-0821 commented on backend/minors/FRE.yaml
> +    - FRE 2*
We can't have both a `course_list` and a `req_list`. Let's put all 2** courses in a requirement, and then put 207 and 208 in the `excluded_work_list`

2024-10-31 16:38 UTC, issacli-0821 approved these changes
Looks good!

2024-10-31 17:38 UTC, merged