new religion yaml
HoagieClub/plan pull request #3
Opened 2024-10-14 23:22 UTC by thutch17

Added in a new yaml for the Religion minor requirements given here: https://religion.princeton.edu/undergraduate/religion-minor.
(apologies if I did anything in the process wrong)

2024-10-15 04:12 UTC, issacli-0821 commented on backend/minors/REL.yaml
> +  explanation: |-
Add `no_req` for requirements we cannot check

2024-10-15 04:16 UTC, issacli-0821 commented on backend/minors/REL.yaml
> +    min_needed: 2
Make sure you include courses from the fall [semester](https://religion.princeton.edu/courses/undergraduate-courses-fall-2024) too!

2024-10-15 04:21 UTC, issacli-0821 commented on backend/minors/REL.yaml
> +    max_counted: 1
We should reorganize the reqs so we only have the "Multiple Areas of Study", and make it have min_needed 2. Then make each of the area a subreq under that with min_needed = 1 and max_counted = 4 to account for the fact that we need a category that has two courses. Feel free to try something else if there's a better way to go about it

2024-10-15 04:21 UTC, issacli-0821 requested changes
Left some comments. Let me know if you have any questions!

2024-10-15 20:20 UTC, thutch17 commented
Should have fixed the comments now :)

2024-10-16 03:11 UTC, issacli-0821 commented on backend/minors/REL.yaml
> +    double_counting_allowed: false
We prob want double_counting to be true, so courses can satisfy the 5-course req and the "Areas of Study"

2024-10-16 03:11 UTC, issacli-0821 requested changes
Left one more comment, and after that we should be good to merge

2024-10-18 18:46 UTC, issacli-0821 approved these changes
Looks good!

2024-10-18 18:46 UTC, merged